trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE

variables:
    ComponentDetection.Timeout: 2400

jobs:
- template: job_templates/olive-perf-monitoring-template.yaml
  parameters:
    name: Windows_CI
    pool: $(OLIVE_POOL_WIN2019)
    windows: True
    examples:
      bert:
        perfMonitoringScriptName: perf_monitoring_models_cpu
        testModel: bert

      bertweet:
        perfMonitoringScriptName: perf_monitoring_models_cpu
        testModel: bertweet
      camembert:
        perfMonitoringScriptName: perf_monitoring_models_cpu
        testModel: camembert

      distilbert:
        perfMonitoringScriptName: perf_monitoring_models_cpu
        testModel: distilbert

      microsoft-deberta:
        perfMonitoringScriptName: perf_monitoring_models_cpu
        testModel: microsoft-deberta

      roberta:
        perfMonitoringScriptName: perf_monitoring_models_cpu
        testModel: roberta

- template: job_templates/olive-perf-monitoring-template.yaml
  parameters:
    name: Linux_CI
    pool: $(OLIVE_POOL_UBUNTU2004)
    windows: False
    examples:
      bert:
        perfMonitoringScriptName: perf_monitoring_models_cpu
        testModel: bert

      bertweet:
        perfMonitoringScriptName: perf_monitoring_models_cpu
        testModel: bertweet
      camembert:
        perfMonitoringScriptName: perf_monitoring_models_cpu
        testModel: camembert

      distilbert:
        perfMonitoringScriptName: perf_monitoring_models_cpu
        testModel: distilbert

      microsoft-deberta:
        perfMonitoringScriptName: perf_monitoring_models_cpu
        testModel: microsoft-deberta

      roberta:
        perfMonitoringScriptName: perf_monitoring_models_cpu
        testModel: roberta
