trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE
pr:
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - examples/README.md
    - examples/**/README.md
    - README.md
    - CONTRIBUTING.md
    - LICENSE

variables:
    ComponentDetection.Timeout: 2400

jobs:
- template: job_templates/olive-perf-monitoring-template.yaml
  parameters:
    name: Windows_CI
    pool: $(OLIVE_POOL_WIN2019)
    windows: True
    examples:
      bert:
        perfMonitoringScriptName: perf_monitoring_models_cpu

- template: job_templates/olive-perf-monitoring-template.yaml
  parameters:
    name: Linux_CI
    pool: $(OLIVE_POOL_UBUNTU2004)
    windows: False
    examples:
      bert:
        perfMonitoringScriptName: perf_monitoring_models_cpu
